# Generated by Django 2.0.7 on 2018-07-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rorender', '0002_machine_running'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='corona_running',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='vray_running',
            field=models.BooleanField(default=True),
        ),
    ]
