# Generated by Django 2.0.7 on 2018-07-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rorender', '0004_machine_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='port',
            field=models.CharField(max_length=200),
        ),
    ]
