# Generated by Django 2.0.7 on 2018-07-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rorender', '0005_auto_20180709_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='corona_running',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='machine',
            name='vray_running',
            field=models.BooleanField(default=False),
        ),
    ]
