# Generated by Django 2.0.7 on 2018-07-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rorender', '0006_auto_20180709_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='rendering',
            field=models.BooleanField(default=False),
        ),
    ]
