# Generated by Django 2.0.7 on 2018-07-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rorender', '0009_machine_is_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='has_autocad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='machine',
            name='has_rhino',
            field=models.BooleanField(default=False),
        ),
    ]
