# Generated by Django 2.0.7 on 2018-08-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rorender', '0010_auto_20180711_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='backburner_running',
            field=models.BooleanField(default=False),
        ),
    ]
