# Generated by Django 3.0.2 on 2020-01-04 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rorender', '0012_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
