# Generated by Django 3.0.2 on 2020-01-04 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rorender', '0013_auto_20200104_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='machine',
        ),
        migrations.AddField(
            model_name='machine',
            name='user',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='rorender.User'),
        ),
    ]
